project_id = "mpxsivfiltwvnvqtixuo"

[functions.mcp-server]
verify_jwt = false

[functions.agent-chat]
verify_jwt = false

[functions.generate-website-content]
verify_jwt = false

[functions.ai-edit-section]
verify_jwt = false

[functions.create-agent-ai]
verify_jwt = false

[functions.whatsapp-agent]
verify_jwt = false

[functions.whatsapp-instance]
verify_jwt = false

[functions.user-api-keys]
verify_jwt = false

[functions.automation-email-blast]
verify_jwt = false

[functions.automation-whatsapp-blast]
verify_jwt = false

[functions.automation-scrape-leads]
verify_jwt = false

[functions.ai-edit-website]
verify_jwt = false
