/**
 * Built-in section emitters.
 *
 * Each emitter produces a JSX expression for one section instance plus an
 * optional component file (registered once per project by the target).
 *
 * Strategy:
 *  - One generated component file per section type: components/sections/<Type>.tsx
 *  - Per-instance JSX is just `<Hero ... />` with the section's props inlined
 *  - The component file itself implements the layout with Tailwind utility classes
 *
 * This keeps the AI out of code emission: it only edits structured props.
 */
import type { ComponentEmitter, EmitContext, EmittedFile, ImportRecord } from "../types";
import type { Project } from "@/core/projects/types";
import { attr, el, escapeAttr, escapeText, fragment, reactComponent, tsxModule } from "../ast/builders";
import { printJsxToString } from "./printJsxToString";
import { printModule } from "../ast/printer";

type SectionPropAttr = { name: string; value: string };

function pascal(input: string): string {
  return input
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase());
}

function attrsFromSection(ctx: EmitContext): SectionPropAttr[] {
  const out: SectionPropAttr[] = [];
  const section = ctx.section ?? {};
  for (const field of ctx.definition.schema.fields) {
    const raw = (section as Record<string, unknown>)[field.key];
    if (raw === undefined || raw === null) continue;
    if (typeof raw === "string") {
      out.push({ name: field.key, value: `"${escapeAttr(raw)}"` });
    } else if (typeof raw === "number" || typeof raw === "boolean") {
      out.push({ name: field.key, value: `{${String(raw)}}` });
    } else {
      out.push({ name: field.key, value: `{${JSON.stringify(raw)}}` });
    }
  }
  return out;
}

function makeSectionEmitter(opts: {
  componentId: string;
  componentName: string;
  filePath: string;
  baseTagline: string;
  renderBody: (ctx: EmitContext) => string;
}): ComponentEmitter {
  return {
    componentId: opts.componentId,

    imports(ctx): ImportRecord[] {
      return [{ module: `@/components/sections/${opts.componentName}`, defaultImport: opts.componentName }];
    },

    emit(ctx) {
      const props = attrsFromSection(ctx).map((p) =>
        p.value.startsWith('"') ? attr.string(p.name, JSON.parse(p.value)) : attr.expr(p.name, p.value.slice(1, -1)),
      );
      props.push(attr.string("data-section-id", ctx.nodeId));
      const node = el(opts.componentName, props);
      return printJsxToString(node);
    },

    files(project: Project): EmittedFile[] {
      const mod = tsxModule(opts.filePath, {
        banner: [opts.baseTagline, `Auto-generated by codegen — do not edit by hand.`],
        imports: [{ module: "react", named: ["type ReactNode"] }],
        declarations: [
          `export interface ${opts.componentName}Props {\n  title?: string;\n  subtitle?: string;\n  description?: string;\n  ctaText?: string;\n  ctaAction?: string;\n  [key: string]: unknown;\n}`,
        ],
        defaultExport: reactComponent(
          opts.componentName,
          el("section", [attr.className("w-full py-16 px-6 md:px-12 bg-background text-foreground")], [
            { kind: "element", name: "div", attrs: [attr.className("max-w-6xl mx-auto")], children: [
              { kind: "expr", value: `/* body */` },
            ] },
          ]),
          {
            params: `(props: ${opts.componentName}Props)`,
            body: [`const { title, subtitle, description, ctaText } = props;`],
          },
        ),
      });
      // Replace body placeholder with rich, type-specific layout
      let source = printModule(mod);
      source = source.replace(`{/* body */}`, opts.renderBody({} as EmitContext));
      return [{ path: opts.filePath, content: source, lang: "tsx", generatedBy: "section-emitter", sources: [opts.componentId] }];
    },
  };
}

/* ---------- Per-type body renderers (Tailwind, semantic markup) ---------- */

const heroBody = () => `<div className="flex flex-col items-center text-center gap-6">
        {title && <h1 className="text-5xl md:text-6xl font-bold tracking-tight">{title}</h1>}
        {subtitle && <p className="text-xl md:text-2xl text-muted-foreground">{subtitle}</p>}
        {description && <p className="max-w-2xl text-base text-muted-foreground">{description}</p>}
        {ctaText && (
          <a href={(props.ctaAction as string) ?? "#"} className="inline-flex items-center justify-center rounded-md bg-primary text-primary-foreground px-6 py-3 text-sm font-medium hover:opacity-90 transition">
            {ctaText}
          </a>
        )}
      </div>`;

const aboutBody = () => `<div className="grid md:grid-cols-2 gap-12 items-center">
        <div>
          {title && <h2 className="text-3xl md:text-4xl font-semibold mb-4">{title}</h2>}
          {subtitle && <p className="text-lg text-muted-foreground mb-6">{subtitle}</p>}
          {description && <p className="text-base leading-relaxed text-muted-foreground">{description}</p>}
        </div>
        <div className="aspect-video w-full rounded-xl bg-muted" aria-hidden="true" />
      </div>`;

const ctaBody = () => `<div className="rounded-2xl bg-primary text-primary-foreground p-10 md:p-16 text-center flex flex-col items-center gap-6">
        {title && <h2 className="text-3xl md:text-4xl font-bold">{title}</h2>}
        {subtitle && <p className="text-lg opacity-90 max-w-2xl">{subtitle}</p>}
        {ctaText && (
          <a href={(props.ctaAction as string) ?? "#"} className="inline-flex items-center justify-center rounded-md bg-background text-foreground px-6 py-3 text-sm font-medium hover:opacity-90 transition">
            {ctaText}
          </a>
        )}
      </div>`;

const genericBody = (label: string) => `<div className="flex flex-col gap-4">
        {title && <h2 className="text-3xl md:text-4xl font-semibold">{title}</h2>}
        {subtitle && <p className="text-lg text-muted-foreground">{subtitle}</p>}
        {description && <p className="text-base text-muted-foreground max-w-3xl">{description}</p>}
        <p className="text-xs uppercase tracking-wider text-muted-foreground">${label}</p>
      </div>`;

export const builtinSectionEmitters: ComponentEmitter[] = [
  makeSectionEmitter({ componentId: "section.hero", componentName: "HeroSection", filePath: "components/sections/HeroSection.tsx", baseTagline: "Hero section.", renderBody: heroBody }),
  makeSectionEmitter({ componentId: "section.about", componentName: "AboutSection", filePath: "components/sections/AboutSection.tsx", baseTagline: "About section.", renderBody: aboutBody }),
  makeSectionEmitter({ componentId: "section.services", componentName: "ServicesSection", filePath: "components/sections/ServicesSection.tsx", baseTagline: "Services section.", renderBody: () => genericBody("services") }),
  makeSectionEmitter({ componentId: "section.features", componentName: "FeaturesSection", filePath: "components/sections/FeaturesSection.tsx", baseTagline: "Features section.", renderBody: () => genericBody("features") }),
  makeSectionEmitter({ componentId: "section.testimonials", componentName: "TestimonialsSection", filePath: "components/sections/TestimonialsSection.tsx", baseTagline: "Testimonials section.", renderBody: () => genericBody("testimonials") }),
  makeSectionEmitter({ componentId: "section.cta", componentName: "CtaSection", filePath: "components/sections/CtaSection.tsx", baseTagline: "Call to action.", renderBody: ctaBody }),
  makeSectionEmitter({ componentId: "section.contact", componentName: "ContactSection", filePath: "components/sections/ContactSection.tsx", baseTagline: "Contact section.", renderBody: () => genericBody("contact") }),
  makeSectionEmitter({ componentId: "section.team", componentName: "TeamSection", filePath: "components/sections/TeamSection.tsx", baseTagline: "Team section.", renderBody: () => genericBody("team") }),
  makeSectionEmitter({ componentId: "section.gallery", componentName: "GallerySection", filePath: "components/sections/GallerySection.tsx", baseTagline: "Gallery section.", renderBody: () => genericBody("gallery") }),
  makeSectionEmitter({ componentId: "section.pricing", componentName: "PricingSection", filePath: "components/sections/PricingSection.tsx", baseTagline: "Pricing section.", renderBody: () => genericBody("pricing") }),
  makeSectionEmitter({ componentId: "section.faq", componentName: "FaqSection", filePath: "components/sections/FaqSection.tsx", baseTagline: "FAQ section.", renderBody: () => genericBody("faq") }),
];

// Suppress unused-import warnings for helpers reserved for future emitters.
void fragment;
void escapeText;
