// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpxsivfiltwvnvqtixuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1weHNpdmZpbHR3dm52cXRpeHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4Nzc3NTQsImV4cCI6MjA4NDQ1Mzc1NH0.OuLNfobmB6GMNmi-9xvx46XKYFgi6WQSxR0h0s2m9vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});